name: backup_notifier
description: Native Android backup notifications for Daftar headless Workmanager tasks.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.akrmcodes.daftar.backup_notifier
        pluginClass: BackupNotifierPlugin
