// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYrRc72AWYOSEoR7qSlmqYzcADGOOXOM',
    appId: '1:1006508283232:android:c85bc6b54075d6346fba05',
    messagingSenderId: '1006508283232',
    projectId: 'daftar-core-prod',
    storageBucket: 'daftar-core-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3N8x_JHMGnjOWI5iaX4EF22agcmGDKkw',
    appId: '1:1006508283232:ios:f966bdc81b9e2b796fba05',
    messagingSenderId: '1006508283232',
    projectId: 'daftar-core-prod',
    storageBucket: 'daftar-core-prod.firebasestorage.app',
    androidClientId: '1006508283232-d81m4q7jt8q3b4r830njsg85b9l1qdsu.apps.googleusercontent.com',
    iosClientId: '1006508283232-aird5krpnqovuu2tcgvi6qhuu6i7ouds.apps.googleusercontent.com',
    iosBundleId: 'com.akrmcodes.daftar',
  );
}
